remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
title: "Eaas MA learning session"
description: "This page contains learning materials for eaas MA learning session"
